[project]
name = "gtkdm"
dynamic = ["version"]
description = "Python GTK Display Manager for EPICS operator interfaces"
readme = "README.md"
license = "MIT"
authors = [
    { name = "Michel Fodje", email = "michel.fodje@lightsource.ca" },
]
keywords = [
    "control-system",
    "display",
    "epics",
    "manager",
    "scada",
]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "pandas",
    "gepics (>=2025.10.3, <2026.0.0)",
    "pygobject (==3.44.2)",
    "PyYAML",
    "tables",
    "matplotlib",
    "numpy (>=1.2.0,<3.0.0)",
]
requires-python = ">=3.9,<4.0"


[project.urls]
Homepage = "https://github.com/michel4j/gtkdm"
Issues = "https://github.com/michel4j/gtkdm/issues"


[tool.poetry]
packages = [
    { include = "gtkdm", from = "." },
]
include = [
    {path = "gtkdm/glade/catalog.xml", format = ["sdist", "wheel"]},
    {path = "gtkdm/glade/style.css", format = ["sdist", "wheel"]},
    {path = "gtkdm/glade/dark.mplstyle", format = ["sdist", "wheel"]},
    {path = "gtkdm/glade/chart-config.ui", format = ["sdist", "wheel"]},
]
version = "0.0.0"


[tool.poetry.scripts]
gtkdm = "gtkdm.scripts:main"
gtkdm-charting = "gtkdm.scripts:charting_main"
gtkdm-editor = "gtkdm.scripts:editor"
gtkdm-migrate = "gtkdm.scripts:migrate"
gtkdm-mksym = "gtkdm.scripts:make_symbol"

[tool.poetry.group.dev.dependencies]
pygobject-stubs = "^2.13.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
format = "{base}.{revision}{distance}"
